version: '3'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: ${MYSQL_KC_PASSWORD}
    ports:
      - 3306:3306

  keycloak:
    build: ./docker
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${MYSQL_KC_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KC_ADMIN_PASSWORD}
#      KEYCLOAK_LOGLEVEL: DEBUG
#      KEYCLOAK_FRONTEND_URL: ${KC_KEYCLOAK_FRONTEND_URL}
    depends_on:
      - mysql
    ports:
      - 8080:8080
